# Generated by Django 6.0.5 on 2026-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('email', models.EmailField(help_text='Unique email address of the student', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20, null=True)),
                ('course', models.CharField(help_text='Course or program the student is enrolled in', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the student record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the student record was last updated')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
